### ISSUE TITLE
Русский язык в UIText

### ISSUE THREAD

**Issue by KorolevAndrey** [NeoAxis/Public#10]
Когда пишу по русски в UIText то там в итоге квадратики на экране

**Comment by betauser6** [comment]
Дополнительные символы указываются в Assets\Base\Fonts\Default.ttf.settings, FlowGraphEditor.ttf.settings.
Впрочем, хорошие новости! В 2020.2 символы кириллицы добавлены по умолчанию.

**Comment by KorolevAndrey** [comment]
ok
