### ISSUE TITLE
Widget WPF Проблема с управлением мышкой, очень быстро двигается и вращается

### ISSUE THREAD

**Issue by KorolevAndrey** [NeoAxis/Public#18]
WPF и скорее всего с WinForms Widget Проблема с управлением мышкой, очень быстро двигается и вращается

[https://www.youtube.com/watch?v=2DGUvOZJies](https://www.youtube.com/watch?v=2DGUvOZJies)

**Comment by IvanEfimov** [comment]
Спасибо, баг с relative mouse mode. в WinForms тоже.

**Comment by IvanEfimov** [comment]
Пофиксилось, будет в следующем обновлении. Еще курсор не скрывался.

**Comment by KorolevAndrey** [comment]
ok
