### ISSUE TITLE
<CaretOnPositionChanged>d__30.MoveNext()

### ISSUE THREAD

**Issue by KorolevAndrey** [NeoAxis/Public#4]
Ошибка при редактировании текста во встроенном редакторе C#
Пропадает при перезапуске и потом по неизвестной причине появляется еще раз через неопределенное время

![5265u345r3](https://user-images.githubusercontent.com/44860813/77574685-705d0f80-6ee3-11ea-9c7a-1308e0c01ce7.jpg)

[errir.txt](https://github.com/NeoAxis/Public/files/4382940/errir.txt)

**Comment by betauser6** [comment]
Не получается поймать баг. Как именно делать?

**Comment by KorolevAndrey** [comment]
не знаю
но вроде я копипастил код ctrl+c , ctrl+v в C# Script и Enter нажимал, потом выскакивает но не всегда, редко, последнее время вообще не выскакивало

**Comment by KorolevAndrey** [comment]
Сегодня опять было, я из одной сцены скопировал в другую сцену грубо говоря коробку с collisionbody и там еще скрипт был на событии simulation step. Сохранил и запускал сценц пару раз. Скопировалось без проблем, но потом я скрипт открыл правой кнопкой Editor и пытался 
заменить число 6 на 10 и мне тут же выскачило

![image](https://user-images.githubusercontent.com/44860813/79451077-9fe8ce80-7fee-11ea-8c88-7a66df94f4be.png)


![image](https://user-images.githubusercontent.com/44860813/79451017-7f207900-7fee-11ea-84c0-c0860a1ddfb7.png)

**Comment by KorolevAndrey** [comment]
ok
