### ISSUE TITLE
3 раза root

### ISSUE THREAD

**Issue by KorolevAndrey** [NeoAxis/Public#5]
при работе со сценой 3 раза появился root и перезапуск не помогает

![3 root](https://user-images.githubusercontent.com/44860813/77574689-718e3c80-6ee3-11ea-9a8f-393e89573e27.jpg)

**Comment by betauser6** [comment]
В текстовом редакторе можно убрать в файле параметр EditorDocumentConfiguration.
Это зачатки multi viewport mode :)

**Comment by KorolevAndrey** [comment]
ok
