### ISSUE TITLE
Gradient_sky и Component_Sky

### ISSUE THREAD

**Issue by KorolevAndrey** [NeoAxis/Public#6]
вместо шейдера Gradient_sky  вставил другой простейщий шейдер

взято с
http://glslsandbox.com/e#62341.0

....
uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;

void main( void ) {
	float time = sin(time) * 1.0;
	vec2 position = ( gl_FragCoord.xy / resolution.xy );
	
	float x = sin(position.x);
	float y = cos(position.y);
	
	gl_FragColor = vec4(vec3(x, y, min(x,y) / time), 1.0);

}
....

![JPEG_20200325_135250](https://user-images.githubusercontent.com/44860813/77576011-7358ff80-6ee5-11ea-9424-61f10e696a72.jpg)

![JPEG_20200325_135308](https://user-images.githubusercontent.com/44860813/77576012-748a2c80-6ee5-11ea-83b7-d4f96b0b154a.jpg)

передаю time так же как в Gradient_sky

generalContainer.Set("time", (float)EngineApp.EngineTime);

но так не работает
пробовал в версии 2019.4

как надо сделать чтобы работало?

**Comment by betauser6** [comment]
vec2 нельзя передавать. только float, vec4, mat3, mat4. может поэтому другие сломались.

**Comment by KorolevAndrey** [comment]
Получилось

в C# вписал так:
generalContainer.Set( "topExponent123", (float)EngineApp.EngineTime );						

а в shader:
.....
uniform vec4 topExponent123;
.....
в main:
нaпример:
float time444 = abs(sin(topExponent123.x)) * 1.0;
