### ISSUE TITLE
Текущее время проигрываемой анимации (current animation time)

### ISSUE THREAD

**Issue by KorolevAndrey** [NeoAxis/Public#7]
Обратил внимание что эти переменные зачем то private и никак нельзя эти данные получить
в компоненте MeshInSpaceAnimationController
Прошу в следующих версиях движка сделать это время доступным read-only.
Иначе костыльным методом приходится делать.
спасибо.

![image](https://user-images.githubusercontent.com/44860813/77846275-9fae9d80-71bd-11ea-8b3b-d2bcae97c1bb.png)

**Comment by betauser6** [comment]
Спасибо первопроходцам!
Свойства появятся в следующем обновлении. Может что-то еще из подобного не хватает.

**Comment by KorolevAndrey** [comment]
в CurveinSpace такая же проблема, но там можно свой класс написать так ,что непонятно

**Comment by KorolevAndrey** [comment]
ok
