### ISSUE TITLE
PlayScreen.cs  - Load( string fileName, bool canChangeUIControl )

### ISSUE THREAD

**Issue by KorolevAndrey** [NeoAxis/Public#9]
В PlayScreen.cs 
функция - Load( string fileName, bool canChangeUIControl )

Если игра в режиме FirstPerson и загрузить новую сцену тоже FirstPerson, то управление мышкой и клавиатурой 'отключается', чтобы заработало опять надо нажать Esc и потом Close

или прошу сообщить как сделать workaround?
Спасибо.

**Comment by betauser6** [comment]
Может метод вызывается где-то из GUI, который сам, собственно, меняется. Как вариант перегружать сцену из SimulationApp.EngineApp_Tick. Сделать метод SimulationApp.NeedChangeScene(string sceneName).

**Comment by KorolevAndrey** [comment]
ок, да сцена грузилась из cs файла UI который в PlayScreen.UIControl

**Comment by KorolevAndrey** [comment]
не помогло

![image](https://user-images.githubusercontent.com/44860813/80531201-e18c5880-89a2-11ea-89bb-096edd631b4f.png)


		public static void LoadSc(String sc)
		{
			string nextLevel = "Store\\AndreyKorolev\\5MinGame\\"+sc+".scene";			                        
                        PlayScreen.Instance.Load(nextLevel, false);
		}

**Comment by KorolevAndrey** [comment]
также - нажатие F7 - происходит, но не помогает

**Comment by KorolevAndrey** [comment]
ok
